### ISSUE TITLE
Keycloak and ORCID

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-user-server#2]
Investigate if Keycloak could support SSO via ORCID identifier.

**Comment by graybeal** [comment]
It appears both support OpenID Connect. See https://orcid.org/blog/2019/04/17/orcid-openid-connect-and-implicit-authentication and https://www.keycloak.org/docs/latest/securing_apps/.

**Comment by marcosmro** [comment]
This conversation is relevant too:
https://groups.google.com/g/orcid-api-users/c/33vLCBymjMg

**Comment by graybeal** [comment]
Please take note of what it will take to upgrade KeyCloak as you go, but hold off on any upgrade until the work for this ticket is released to production.

**Comment by martinjoconnor** [comment]
Released in 2.6.18
