### ISSUE TITLE
ORCID ID linkage options for VFB

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-user-server#6]
When OAuth authentication (e.g., GitHub) is used in CEDAR, KeyCloak gives the user a CEDAR account and we generate a CEDAR User ID (and eventually folder) for the user. For cases like ORCID, it is useful to be able to look up the original ORCID identifier from the CEDAR user ID (and eventually, the other way around).

The question in this task is whether the existing CEDAR users endpoint already returns this additional metadata (the ORCID ID) for a CEDAR user, and if not, what will it take to make sure that metadata exists in KeyCloak and can be retrieved by CEDAR and made available via the users REST API. 

See also https://github.com/metadatacenter/cedar-user-server/issues/2.

**Comment by martinjoconnor** [comment]
Released in 2.6.18.
